language: java

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)